<?php

namespace Ferus\AccountBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountRepository extends EntityRepository
{
    public function findOneByStudentId($id)
    {
        return $this->createQueryBuilder('a')
            ->where('IDENTITY(a.student) = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getSingleResult();
    }
}
