<?php

namespace Ferus\EventBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EventOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventOptionRepository extends EntityRepository
{
}
