<?php

namespace Ferus\EventBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    public function queryAll()
    {
        return $this->createQueryBuilder('e')
            ->orderBy('e.date', 'DESC');
    }
}
