<?php

namespace Ferus\SellerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SellerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SellerRepository extends EntityRepository
{
}
