<?php

namespace Ferus\SellerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SellerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SellerRepository extends EntityRepository
{
    public function findOneByBarcode($barcode)
    {
        return $this->createQueryBuilder('se')
            ->where('se.id = :barcode')
            ->setParameter('barcode', substr($barcode, 1))
            ->getQuery()
            ->getSingleResult();
    }
}
