<?php

namespace Ferus\StudentBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentRepository extends EntityRepository
{
    public function queryAll()
    {
        return $this->createQueryBuilder('s')
            ->getQuery();
    }
}
