<?php

namespace Ferus\FCFSBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * EventRegistrationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRegistrationRepository extends EntityRepository
{
    public function findData(Event $event)
    {
        return $this->createQueryBuilder('r')
            ->select('s.id, CONCAT(s.lastName, CONCAT(\' \', s.firstName)) name, s.email, r.createdAt')
            ->join('r.student', 's')
            ->orderBy('s.lastName', 'ASC')
            ->where('r.event = :event')
            ->setParameter('event', $event)
            ->getQuery()
            ->getResult(Query::HYDRATE_ARRAY);
    }
}
