<?php

namespace Ferus\FCFSBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventRegistrationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRegistrationRepository extends EntityRepository
{
}
