<?php

namespace Ferus\TransactionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionRepository extends EntityRepository
{
    public function findLast($max = 50)
    {
        return $this->createQueryBuilder('t')
            ->setMaxResults($max)
            ->orderBy('t.completedAt', 'DESC')
            ->getQuery()->getResult();
    }
}
