<?php

namespace Ferus\MailBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AuthRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthRepository extends EntityRepository
{
    public function queryAll()
    {
        return $this->createQueryBuilder('a')
            ->orderBy('a.createdAt', 'DESC');
    }
}
