<?php

namespace Ferus\MailBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AuthorityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorityRepository extends EntityRepository
{
    public function findOneByEmail($email)
    {
        return $this->createQueryBuilder('a')
            ->where('a.email = :email')
            ->setParameter('email', preg_replace('#^.*<(.+)>.*$#', '$1', $email))
            ->getQuery()
            ->getSingleResult();
    }
}
