<?php

namespace Ferus\MailBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ResponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResponseRepository extends EntityRepository
{
    public function responseExist($id)
    {
        return $this->createQueryBuilder('r')
            ->select('COUNT(r)')
            ->where('r.messageUid = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getSingleScalarResult() > 0;
    }
}
