<?php

namespace Ferus\MailBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemplateRepository extends EntityRepository
{
    public function findAll()
    {
        return $this->createQueryBuilder('t')
            ->orderBy('t.name')
            ->getQuery()
            ->getResult();
    }
}
